config/routes.rb
Rails.application.routes.draw do

  root   'accounts#welcome'

  get    'login'                          => 'accounts#login_form',         as: :login_form
  post   'login'                          => 'accounts#login',              as: :login_action
  get    'logout'                         => 'accounts#logout',             as: :logout
  get    'signup'                         => 'accounts#signup_form',        as: :signup_form
  post   'signup'                         => 'accounts#signup',             as: :signup_action
  get    'account'                        => 'accounts#show',               as: :account_show

  get    'friends'                        => 'friends#index',               as: :friends
  get    'friends/search'                 => 'friends#search',              as: :friends_search_form
  get    'friends/search/:search_string'  => 'friends#search_action',       as: :friends_search_action
  get    'friends/:id'                    => 'friends#show',                as: :friends_show
  post   'friends/:id'                    => 'friends#add',                 as: :friends_add
  post   'friends/confirm/:id'            => 'friends#confirm',             as: :friends_confirm
  delete 'friends/:id'                    => 'friends#delete',              as: :friends_delete

  get    'games'                          => 'games#index',                 as: :games
  get    'games/search'                   => 'games#search',                as: :games_search_form
  get    'games/search/:search_string'    => 'games#search_action',         as: :games_search_action
  get    'games/:bgg_id'                  => 'games#show',                  as: :games_show
  post   'games/:bgg_id'                  => 'games#add',                   as: :games_add
  delete 'games/:bgg_id'                  => 'games#delete',                as: :games_delete

  get    'events'                         => 'events#index',                as: :events
  post   'events'                         => 'events#new_action',           as: :events_new
  get    'events/new'                     => 'events#new',                  as: :events_new_form
  get    'events/:id/update'              => 'events#update',               as: :events_update_form
  get    'events/:id'                     => 'events#show',                 as: :event
  post   'events/:id'                     => 'events#update_action',        as: :events_update
  post   'events/:id/respond'             => 'events#respond',              as: :events_respond
  delete 'events/:id'                     => 'events#delete',               as: :events_delete

end

app/models/event.rb
class Event < ActiveRecord::Base
  include Status
  include Utility

  belongs_to :host, class_name: "User"
  has_many :game_events
  has_many :games, through: :game_events
  has_many :game_event_votes
  has_many :invitations
  has_many :users, through: :invitations

  def get_invited_users
    others = User
      .joins("INNER JOIN invitations inv ON inv.user_id = users.id")
      .joins("INNER JOIN events e ON inv.event_id = e.id")
      .where("e.id = ?", self.id)
      .first(500)
    others.push self.host
  end

  def get_attending_users
    others = User
      .joins("INNER JOIN invitations inv ON inv.user_id = users.id")
      .joins("INNER JOIN events e ON inv.event_id = e.id")
      .where("e.id = ?", self.id)
      .where("inv.status = ?", Status::ACCEPTED)
      .first(500)
    others.push self.host
  end

  def host
    User.find(self.host_id)
  end

  def get_available_games
    users = self.get_attending_users
    Game
      .joins("INNER JOIN library_games lg ON lg.game_id = games.id")
      .joins("INNER JOIN libraries lib ON lg.library_id = lib.id")
      .joins("INNER JOIN users u ON lib.id = u.library_id")
      .where("u.id in (?)", users)
  end

  def modify(event_hash)
    self.start_time = Utility.to_active_record(event_hash[:datetime])
    self.place = event_hash[:place]
    self.description = event_hash[:description]

    previously_invited_users = self.get_invited_users
    previously_invited_user_ids = previously_invited_users.map{|user| user.id}

    # Add newly invited users
    newly_invited_friend_ids = event_hash[:friend_invite_ids].map{ |id| id.to_i }
    newly_invited_friend_ids.each do |friend_id|
      friend = User.find(friend_id)
      unless friend.in?(previously_invited_users)
        Invitation.invite(self, friend)
      end
    end

    # Remove uninvited users
    reject_ids = previously_invited_user_ids - newly_invited_friend_ids
    reject_ids.each do |reject_id|
      friend = previously_invited_users.select{|user| user.id == reject_id}
      Invitation.destroy_all(event: self, user:friend)
    end
  end

  def cancel

    # TODO: Destroy related invitations

    self.destroy
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :update, :update_action, :delete]


  # GET /events
  def index
    @upcoming_events = @current_user.get_upcoming_events
    @past_events = @current_user.get_past_events
  end

  # GET /events/1
  def show
    @attendees = @event.get_attending_users
    @games = @event.get_available_games
    @invitation = Invitation.find_by_event(@event.id, @current_user)
  end

  def respond
    event_id = params[:id]
    response = params[:response]
    if Invitation.respond_to_event(event_id, response, @current_user)
      if response == Status::ACCEPTED
        flash[:success] = "Invitation accepted!"
      elsif response == Status::PENDING
        flash[:success] = "Invitation rejected."
      end
    end
    render text: 'success'
  end

  # GET /events/new
  def new
    @event = Event.new
    @friends = @current_user.get_friends
    @invited_friends = []
  end

  # POST /events
  def new_action
    @event = Event.new(host: @current_user)

    event_hash = {
      datetime: params[:datetime],
      place: params[:place],
      description: params[:description],
      friend_invite_ids: params[:friend_invite_ids].split(',')
    }
    @event.modify(event_hash)

    if @event.save
      flash['success'] = 'Event was successfully created.'
      redirect_to @event
    else
      flash['error'] = 'There was a problem creating this event.'
      redirect_to :new
    end
  end


  def update

    unless allowed_to_update
      redirect_to :events
    end

    @friends = @current_user.get_friends
    @invited_friends = @event.get_invited_users
  end


  # POST /events/1
  def update_action

    unless allowed_to_update
      redirect_to :events
    end

    event_hash = {
      datetime: params[:datetime],
      place: params[:place],
      description: params[:description],
      friend_invite_ids: params[:friend_invite_ids].split(',')
    }

    @event.modify(event_hash)

    if @event.save
      flash['success'] = 'Event was successfully updated.'
      redirect_to @event
    else
      flash['error'] = 'There was a problem updating this event.'
      redirect_to @event
    end
  end

  # DELETE /events/1
  def delete
    @event.cancel
    flash['success'] = 'Event was successfully deleted.'
    render text: 'success'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Make sure that a user owns an event for them to make changes
    def allowed_to_update
      @event.host == @current_user
    end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if context == :new %>
<form id="event_form" class="event_form" method="POST" action="/events">
<% elsif context == :update %>
<form id="event_form" class="event_form" method="POST" action="/events/<%= @event.id %>">
<% end %>
  <div class="row">
    <%= label_tag :datetime, "Date and Time: " %>
    <div class='input-group date' id='datetime-picker'>
      <input type='text' name="datetime" id="time" class="form-control"
        value="<%= Utility.from_active_record(@event.start_time)%>"/>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <div class="row">
  <%= label_tag :place, "Place: " %>
  <%= text_field_tag :place, @event.place, class: "form-control" %>
  </div>

  <div class="row">
  <%= label_tag :description, "Description: " %>
  <%= text_area_tag :description, @event.description, class: "form-control event-description" %>
  </div>

  <div class="row">
  <h2>Select Friends to Invite:</h2>
  <%= render partial: "friends/list_friends", locals: {users: @friends, page: :event, event: @event} %>
  <input name="friend_invite_ids" type="hidden" />
  </div>

  <div class="row">
  <% if context == :new %>
  <%= link_to 'Cancel', events_path, class: "btn btn-default" %>
  <button class="btn btn-primary" id="submit_button" type="submit" >Create Event</button>
  <% elsif context == :update %>
  <%= link_to 'Cancel', @event, class: "btn btn-default" %>
  <button class="btn btn-primary" id="submit_button" type="submit" >Update Event</button>
  <% end %>
  </div>


  <%= hidden_field_tag :redirect_path, flash[:redirect_path]%>
  <%= token_tag form_authenticity_token %>
</form>

<script type="text/javascript">
$(function () {
  $('#datetime-picker').datetimepicker();

  var default_date = $('#datetime-picker').find('input[name="datetime"]').val();
  $('#datetime-picker').data("DateTimePicker").defaultDate(default_date);

  $('.friend-well').click(function(){
    $(this).toggleClass('selected')
  });

  $('#submit_button').click(function(e){

    e.preventDefault();

    /* Populate the list of selected friend IDs */
    $('input[name="friend_invite_ids"]').val('');
    $('.friend-well.selected').each(function(){
      var id = $(this).find('.friend_id').val();
      var friend_id_list = $('input[name="friend_invite_ids"]').val();
      $('input[name="friend_invite_ids"]').val(friend_id_list + id + ',');
    });
    var friend_id_list = $('input[name="friend_invite_ids"]').val();
    $('input[name="friend_invite_ids"]').val(friend_id_list.substring(0, friend_id_list.length - 1));

    $('#event_form').submit();
  });

});
</script>

app/views/events/_list_events.html.erb
<% if events.empty? %>
  <% if type == :past %>
  <p class="margin-top">
    You have no past events.
  </p>
  <% elsif type == :upcoming %>
  <p class="margin-top">
    You have no upcoming events.
    Why not <%= link_to "host one", :events_new_form %>?
  </p>
  <% end %>
<% else %>
  <div class="row table-header">
    <div class="col-md-3 col-sm-4">Event</div>
    <div class="col-md-3 col-sm-4">Date/Time</div>
  </div>
  <div class="table-body">
    <% events.each do |event| %>
    <div class="row table-row">
      <div class="table-cell col-md-3 col-sm-4">
        <%= link_to "Games at #{event.place}", event %>
      </div>
      <div class="table-cell col-md-3 col-sm-4">
      <%= Utility.from_active_record(event.start_time) %>
      </div>
      <% if type == :upcoming &&  %>
        <% if event.host == @current_user %>
        <div class="table-cell col-md-3 col-sm-4">
          <%= link_to 'Edit', events_update_form_path(event) %>
          &nbsp;
          <%= link_to 'Cancel', "/events/#{event.id}", class: "event-delete" %>
        </div>
        <% else %>
        <% invitation = Invitation.find_by_event(event.id, @current_user) %>
          <% if invitation.status == Status::PENDING %>
          <div class="table-cell col-md-3 col-sm-4">
            <%= link_to 'Accept', "/events/#{event.id}/respond", class: "event-accept" %>
            &nbsp;
            <%= link_to 'Reject', "/events/#{event.id}/respond", class: "event-reject" %>
          </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </tbody>
<% end %>

<script>
$('.event-accept').click(function(e){
  e.preventDefault();
  $.ajax({
    url: this.href,
    method: 'POST',
    data: {response: '<%= Status::ACCEPTED %>'},
    success: function(){
      window.location.reload();
    }
  });
});

$('.event-reject').click(function(e){
  e.preventDefault();
  $.ajax({
    url: this.href,
    method: 'POST',
    data: {response: '<%= Status::REJECTED %>'},
    success: function(){
      window.location.reload();
    }
  });
});

$('.event-delete').click(function(e){
  e.preventDefault();
  if(confirm("Are you sure you want to cancel this event?")){
    $.ajax({
      url: this.href,
      method: 'DELETE',
      success: function(){
        window.location.reload();
      }
    });
  }
});
</script>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>

<%= render 'list_events', events: @upcoming_events, type: :upcoming%>

<br>
<br>
<br>

<h1>Past Events</h1>

<%= render 'list_events', events: @past_events, type: :past%>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render 'form', event: @event, context: :new %>

app/views/events/show.html.erb
<h1 class="show-title"><%= "Games at " + @event.place %></h1>
<% if @event.host == @current_user %>
<%= link_to 'Edit', events_update_form_path(@event) %>
&nbsp;
<%= link_to 'Delete', events_delete_path(@event), class: "event-delete" %>
  <br>
  <br>
<% elsif @invitation && @invitation.status == Status::PENDING %>
<div>
  <%= link_to 'Accept', "/events/#{@event.id}/respond", class: "event-accept" %>
  &nbsp;
  <%= link_to 'Reject', "/events/#{@event.id}/respond", class: "event-reject" %>
  <br>
  <br>
</div>
<% end %>

<div class="row">
<% event_data = {
      :'Description' => "#{@event.description.empty? ? '(None)' : @event.description }",
      :'Time' => "#{Utility.from_active_record @event.start_time}",
      :'Place' => "#{@event.place}",
    } %>
  <div class="col-md-6 col-xs-12">
    <div class="well">
      <% event_data.each do |key, value| %>
      <div class="row">
        <div class="col-md-3 col-xs-12">
          <strong><%= key %>:</strong>
        </div>
        <div class="col-md-9 col-xs-12">
          <%= value %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<h2>Attending</h2>
<div class="row">
  <%= render partial: "friends/list_friends", locals: {users: @attendees, page: :event_show} %>
</div>

<h2>Available Games</h2>
<% @games.each do |game| %>
<div class="row">
  <div class="col-md-6 col-xs-12">
    <p><%= link_to game.title, "/games/#{game.bgg_id}" %></p>
  </div>
</div>
<% end %>

<script>
$('.event-accept').click(function(e){
  e.preventDefault();
  $.ajax({
    url: this.href,
    method: 'POST',
    data: {response: '<%= Status::ACCEPTED %>'},
    success: function(){
      window.location.reload();
    }
  });
});

$('.event-reject').click(function(e){
  e.preventDefault();
  $.ajax({
    url: this.href,
    method: 'POST',
    data: {response: '<%= Status::REJECTED %>'},
    success: function(){
      window.location.reload();
    }
  });
});
$('.event-delete').click(function(e){
  e.preventDefault();
  if(confirm("Are you sure you want to cancel this event?")){
    $.ajax({
      url: this.href,
      method: 'DELETE',
      success: function(){
        window.location = '/events';
      }
    });
  }
});
</script>

app/views/events/update.html.erb
<h1>Update Your Event</h1>

<%= render 'form', event: @event, context: :update %>