config/routes.rb
Rails.application.routes.draw do

  root   'accounts#welcome'

  get    'login'                          => 'accounts#login_form',         as: :login_form
  post   'login'                          => 'accounts#login',              as: :login_action
  get    'logout'                         => 'accounts#logout',             as: :logout
  get    'signup'                         => 'accounts#signup_form',        as: :signup_form
  post   'signup'                         => 'accounts#signup',             as: :signup_action
  get    'account'                        => 'accounts#show',               as: :account_show

  get    'friends'                        => 'friends#index',               as: :friends
  get    'friends/search'                 => 'friends#search',              as: :friends_search_form
  get    'friends/search/:search_string'  => 'friends#search_action',       as: :friends_search_action
  get    'friends/:id'                    => 'friends#show',                as: :friends_show
  post   'friends/:id'                    => 'friends#add',                 as: :friends_add
  post   'friends/confirm/:id'            => 'friends#confirm',             as: :friends_confirm
  delete 'friends/:id'                    => 'friends#delete',              as: :friends_delete

  get    'games'                          => 'games#index',                 as: :games
  get    'games/search'                   => 'games#search',                as: :games_search_form
  get    'games/search/:search_string'    => 'games#search_action',         as: :games_search_action
  get    'games/:bgg_id'                  => 'games#show',                  as: :games_show
  post   'games/:bgg_id'                  => 'games#add',                   as: :games_add
  delete 'games/:bgg_id'                  => 'games#delete',                as: :games_delete

  get    'events'                         => 'events#index',                as: :events
  post   'events'                         => 'events#new_action',           as: :events_new
  get    'events/new'                     => 'events#new',                  as: :events_new_form
  get    'events/:id/update'              => 'events#update',               as: :events_update_form
  get    'events/:id'                     => 'events#show',                 as: :event
  post   'events/:id'                     => 'events#update_action',        as: :events_update
  post   'events/:id/respond'             => 'events#respond',              as: :events_respond
  delete 'events/:id'                     => 'events#delete',               as: :events_delete

end

app/models/game.rb
class Game < ActiveRecord::Base
	include Status
  require 'net/http'
  require 'erb'

  has_many :library_games
  has_many :libraries, through: :library_games
  has_many :game_events
  has_many :events, through: :game_events


  def self.owners(bgg_id)
    User
      .joins('INNER JOIN libraries l ON l.id = users.library_id')
      .joins('INNER JOIN library_games lg ON lg.library_id = l.id')
      .joins('INNER JOIN games g ON lg.game_id = g.id')
      .where("g.bgg_id = ?", bgg_id)
      .first(500)
  end


  def self.by_user(user)
    unless user && user.library_id
      return []
    end

    Game
      .joins(:libraries)
      .where("library_id = ?", user.library_id)
      .order("games.title")
  end


  def self.create_from_bgg(bgg_data)
    bgg_rank = 0
    begin
      bgg_rank = bgg_data['statistics']['ratings']['ranks']['rank']
                    .select{ |ranking| ranking['name'] == 'boardgame'}[0]['value']
    rescue
      bgg_rank = ""
    end
    game_title = bgg_data['name']

    if game_title.is_a?(Array)
      game_title = game_title.select{ |name| name['type'] == 'primary' }[0]['value']
    else
      game_title = game_title['value']
    end

    game_data = {
      title: game_title,
      bgg_id: bgg_data['id'],
      bgg_rating: bgg_data['statistics']['ratings']['average']['value'],
      bgg_rank: bgg_rank,
      bgg_min_players: bgg_data['minplayers']['value'],
      bgg_max_players: bgg_data['maxplayers']['value'],
      bgg_image: bgg_data['image'],
      bgg_playing_time: bgg_data['playingtime']['value']
    }

    Game.create(game_data)

  end


  # Search the BoardGameGeek database for games
  def self.bgg_search(unencoded_search_string)

    search_string = ERB::Util.url_encode(unencoded_search_string)

    url_string = 'http://www.boardgamegeek.com/xmlapi2/search?type=boardgame&query=' + search_string
    Game.api_request(url_string)

  end

  # Retrieve data from BoardGameGeek about a game
  def self.bgg_show(bgg_id)

    url_string = 'http://www.boardgamegeek.com/xmlapi2/thing?stats=1&id=' + bgg_id
    Game.api_request(url_string)['items']['item']

  end

  # Wrapper for making API requests
  def self.api_request(url_string)
    url = URI.parse(url_string)
    request = Net::HTTP::Get.new(url.to_s)
    response = Net::HTTP.start(url.host, url.port) {|http|
      http.request(request)
    }
    Hash.from_xml(response.body)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    unless @current_user.library_id
      flash[:error] = "This account has no associated game library!"
      @games = []
      render and return
    end

    @games = Game.by_user(@current_user)

  end


  def show
    bgg_id = params[:bgg_id]

    @game = Game.where(bgg_id: bgg_id).first
    unless @game
      bgg_data = Game.bgg_show(bgg_id)
      @game = Game.create_from_bgg(bgg_data)
    end

    @owners = Game.owners(bgg_id)

    response = Game.bgg_show(bgg_id)
  end


  def search
    # Just render the form
  end


  def search_action
    search_string = params[:search_string]
    response = Game.bgg_search(search_string)
    @games = response['items']['item'] ? response['items']['item'] : []
    @owned_game_bgg_ids = Game.by_user(@current_user).map { |game| game.bgg_id.to_s }
    logger.info '************************'
    logger.info @owned_game_bgg_ids
    logger.info '************************'
  end


  def add
    bgg_id = params[:bgg_id]
    game_in_db = Game.where("bgg_id = ?", bgg_id).first
    if game_in_db
      @game = game_in_db
    else
      bgg_data = Game.bgg_show(bgg_id)
      @game = Game.create_from_bgg(bgg_data)
    end

    LibraryGame.create(library: @current_user.library, game: @game)

    render text: 'success'

  end


  def delete
    bgg_id = params[:bgg_id]
    @game = Game.where(bgg_id: bgg_id).first
    LibraryGame.where(library: @current_user.library, game: @game).destroy_all

    render text: 'success'
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :last_sync %><br>
    <%= f.datetime_select :last_sync %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/_game_search.html.erb
<div class="col-md-4 col-sm-12">
  <div class="input-group game-search-bar">
    <input type="text" class="form-control game-search-input" placeholder="Search for...">
    <span class="input-group-btn">
      <button class="btn btn-default game-search-button" type="button">
        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
      </button>
    </span>
  </div>
</div>
<script>
  $('.game-search-button').click(function(){
    var search_string = $('.game-search-input').val();
    window.location = '/games/search/' + encodeURIComponent(search_string);
  });
  $(".game-search-input").keypress(function(e) {
    if(e.keyCode == 13){
       e.preventDefault();
       $('.game-search-button').click();
    }
  });
</script>

app/views/games/_list_games.html.erb
<% if @games.empty? %>
  <div class="col-md-6 no-results-message">
    <% if context == :list %>
    Your library is empty. <%= link_to 'Find your games', games_search_form_url %>.
    <% elsif context == :search %>
    No results found!
    <% end %>
  </div>
<% else %>

  <% if context == :list %>
  <div class="row table-header">
    <div class="col-md-2 col-sm-4">Title</div>
    <div class="col-md-2 col-sm-4">BGG Rank</div>
    <div class="col-md-2 col-sm-4">Players</div>
    <div class="col-md-2 col-sm-4">Playing Time</div>
  </div>
  <div class="table-body">
    <% @games.each do |game| %>
      <div class="row table-row">
        <div class="table-cell col-md-2 col-sm-4">
        <%= link_to game.title, "/games/#{game.bgg_id}" %>
        </div>
        <div class="table-cell col-md-2 col-sm-4"><%= game.bgg_rank || 'Not Ranked' %></div>
        <div class="table-cell col-md-2 col-sm-4">
          <%= game.bgg_min_players %> - <%= game.bgg_max_players %>
        </div>
        <div class="table-cell col-md-2 col-sm-4"><%= game.bgg_playing_time %> Minutes</div>
        <div class="table-cell col-md-2 col-sm-4">
          <%= link_to 'Delete', "/games/#{game.bgg_id}", class: "game-delete" %>
        </div>
      </div>
    <% end %>
  </div>
  <% elsif context == :search %>
  <div class="row table-header">
    <div class="col-md-6">Game</div>
  </div>
  <div class="table-body">
    <% @games.each do |game| %>
      <div class="row table-row">
        <div class="table-cell col-md-6">
        <%= link_to game['name']['value'], "/games/#{game['id']}" %>
        </div>
        <div class="table-cell col-md-2 col-sm-3">
          <% if @owned_game_bgg_ids.include?(game['id']) %>
            Already in Library
          <% else %>
            <%= link_to 'Add to Library', "/games/#{game['id']}", class: "game-add" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
<% end %>

<script>
$('.game-add').click(function(e){
  e.preventDefault();
  $.ajax({
      url: this.href,
      method: 'POST',
      success: function(){
        window.location.reload();
      }
  });
});
$('.game-delete').click(function(e){
  e.preventDefault();
  if(confirm("Are you sure you want to remove this game from your library?")){
    $.ajax({
      url: this.href,
      method: 'DELETE',
      success: function(){
        window.location.reload();
      }
    });
  }
});
</script>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Game Library</h1>

<%= render partial: "list_games", locals: {games: @games, context: :list} %>

<br>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/search.html.erb
<h1>Search for your games</h1>
<br/>
<div class="row">
  <%= render partial: "game_search" %>
</div>

app/views/games/search_action.html.erb
<h1>Search for your games</h1>
<br/>
<div class="row">
  <%= render partial: "game_search" %>
</div>

<%= render partial: "list_games", locals: {games: @games, context: :search} %>

app/views/games/show.html.erb
<h1 class="show-title"><%= @game.title %></h1>
<div class="row">
  <div class="col-xs-4">
    <%= image_tag "#{@game.bgg_image}", class: "game-image" %>
  </div>
  <% game_data = {
      :'Players' => "#{@game.bgg_min_players} - #{@game.bgg_max_players}",
      :'Playing Time' => "#{@game.bgg_playing_time}",
      :'BGG Rank' => "#{@game.bgg_rank ? @game.bgg_rank : 'Not Ranked'}",
      :'BGG Rating' => "#{@game.bgg_rating}",
    } %>
  <div class="col-xs-4">
    <div class="well">
      <% game_data.each do |key, value| %>
      <div class="row">
        <div class="col-md-6 col-xs-12">
          <strong><%= key %>:</strong>
        </div>
        <div class="col-md-6 col-xs-12">
          <%= value %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<h1>Users with this game:</h1>
<% @owners.each do |user|%>
  <p><%= link_to user.name, "/friends/#{user.id}" %></p>
<% end %>