config/routes.rb
Rails.application.routes.draw do

  root   'accounts#welcome'

  get    'login'                          => 'accounts#login_form',         as: :login_form
  post   'login'                          => 'accounts#login',              as: :login_action
  get    'logout'                         => 'accounts#logout',             as: :logout
  get    'signup'                         => 'accounts#signup_form',        as: :signup_form
  post   'signup'                         => 'accounts#signup',             as: :signup_action
  get    'account'                        => 'accounts#show',               as: :account_show

  get    'friends'                        => 'friends#index',               as: :friends
  get    'friends/search'                 => 'friends#search',              as: :friends_search_form
  get    'friends/search/:search_string'  => 'friends#search_action',       as: :friends_search_action
  get    'friends/:id'                    => 'friends#show',                as: :friends_show
  post   'friends/:id'                    => 'friends#add',                 as: :friends_add
  post   'friends/confirm/:id'            => 'friends#confirm',             as: :friends_confirm
  delete 'friends/:id'                    => 'friends#delete',              as: :friends_delete

  get    'games'                          => 'games#index',                 as: :games
  get    'games/search'                   => 'games#search',                as: :games_search_form
  get    'games/search/:search_string'    => 'games#search_action',         as: :games_search_action
  get    'games/:bgg_id'                  => 'games#show',                  as: :games_show
  post   'games/:bgg_id'                  => 'games#add',                   as: :games_add
  delete 'games/:bgg_id'                  => 'games#delete',                as: :games_delete

  get    'events'                         => 'events#index',                as: :events
  post   'events'                         => 'events#new_action',           as: :events_new
  get    'events/new'                     => 'events#new',                  as: :events_new_form
  get    'events/:id/update'              => 'events#update',               as: :events_update_form
  get    'events/:id'                     => 'events#show',                 as: :event
  post   'events/:id'                     => 'events#update_action',        as: :events_update
  post   'events/:id/respond'             => 'events#respond',              as: :events_respond
  delete 'events/:id'                     => 'events#delete',               as: :events_delete

end

app/views/layouts/_navbar_account_widget.html.erb
<% if user %>
  <ul class="nav navbar-nav">
    <li><p class="navbar-text"><%= user.name %></p></li>
    <li id="navbar-logout"><a id="logout" href="/logout">Log out</a></li>
  </ul>
<% else %>
  <form id="navbar-login" class="form-inline" method="post" action="/login">
    <div class="form-group">
      <input type="text" class="form-control" name="email" placeholder="Email">
      <input type="password" class="form-control" name="password" placeholder="Password">
    </div>
    <button type="submit" method="post" class="btn btn-default">Login</button>
    <a href="/signup" class="btn btn-default">Sign Up</a>
    <%= token_tag form_authenticity_token %>
  </form>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>GameNight</title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-logo" href="/">
           <%= image_tag "GameNight-logo.png", alt: "GameNight", size: "150x50" %>
        </a>
      </div>

      <div class="nav navbar-nav navbar-right">
        <%= render 'layouts/navbar_account_widget', user: @current_user %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

          <li class="dropdown" >
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >
              Friends
              <% if @friend_requests && @friend_requests.size > 0 %>
                <span class="badge"><%= @friend_requests.size %></span>
              <% end %>
              <span class="caret"></span>
            </a>

            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'My Friends', friends_url %></li>
              <li><%= link_to 'Search for Friends', friends_search_form_url %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >
              Games<span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'My Games', games_url %></li>
              <li><%= link_to 'Add New Games', games_search_form_url %></li>
            </ul>
          </li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >
              Events
              <% if @event_invites && @event_invites.size > 0 %>
                <span class="badge"><%= @event_invites.size %></span>
              <% end %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'My Events', events_url %></li>
              <li><%= link_to 'Create New Event', events_new_form_url %></li>
            </ul>
          </li>

        </ul>
      </div>

    </div>
  </nav>

  <!-- Page Content -->
  <div id="main-content" class="container">

    <!-- Flash messages -->
    <div class="row">
    <% flash.each do |key, value| %>
      <% if key == 'success' %>
        <div class="alert alert-success alert-dismissible" role="alert">
        <%= value %>
        <button class="close" data-dismiss="alert">&times;</button>
        </div>
      <% elsif key == 'error' %>
        <div class="alert alert-danger alert-dismissible" role="alert">
        <%= value %>
        <button class="close" data-dismiss="alert">&times;</button>
        </div>
      <% end %>
    <% end %>
    </div>

    <!-- Main content -->
    <%= yield %>

  </div>
  <!-- /.container -->

  <!-- For Rails CSRF protection -->
  <%= csrf_meta_tags %>
</body>
</html>